#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh install.sh
      cmd < build.bat
      mv boost/bin.v2 libtorrent/bin/boost
  - publish: $(System.DefaultWorkingDirectory)/libtorrent/bin
    artifact: libtorrent-win32

- job: win64
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh install.sh
      cmd < build.bat
      mv boost/bin.v2 libtorrent/bin/boost
  - publish: $(System.DefaultWorkingDirectory)/libtorrent/bin
    artifact: libtorrent-win64
