#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh generate.sh win32
      cd ../s
      sh build.sh win32
      cd deploy
      7z a ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-win32

- job: win64
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh generate.sh win64
      cd ../s
      sh build.sh win64
      cd deploy
      7z a ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-win64

#--------------------------------------------------------------------------------------------------

- job: win32_msvc
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh environment.sh msvc
      sh generate.sh win32
      cd ../s
      sh build.sh win32-msvc
      cd deploy
      7z a ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-win32-msvc

- job: win64_msvc
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh environment.sh msvc
      sh generate.sh win32
      cd ../s
      sh build.sh win64-msvc
      cd deploy
      7z a ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-win64-msvc

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS
  pool:
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh build.sh macOS
      cd deploy
      zip -rq ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-macOS

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

# NOTE: We need a linux32_qt4 build for ubuntu:18.04.
- job: linux32_qt4
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/libtorrent i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /libtorrent/..;
                                     apt-get update;
                                     apt-get -y install sudo zip git;
                                     git clone https://github.com/omega-gg/libtorrent;
                                     cd libtorrent;
                                     sh build.sh linux;
                                     cd deploy;
                                     zip -rq ../libtorrent.zip *"
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-linux32-qt4

- job: linux32
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/libtorrent i386/ubuntu:20.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /libtorrent/..;
                                     apt-get update;
                                     apt-get -y install sudo zip git;
                                     git clone https://github.com/omega-gg/libtorrent;
                                     cd libtorrent;
                                     sh build.sh linux;
                                     cd deploy;
                                     zip -rq ../libtorrent.zip *"
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-linux32

- job: linux64
  pool:
    vmImage: "ubuntu-latest"
  steps:
  # NOTE: We need an older version to package the application.
  - bash: |
      docker run -d --name ubuntu -v $PWD:/libtorrent amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /libtorrent/..;
                                     apt-get update;
                                     apt-get -y install sudo zip git;
                                     git clone https://github.com/omega-gg/libtorrent;
                                     cd libtorrent;
                                     sh build.sh linux;
                                     cd deploy;
                                     zip -rq ../libtorrent.zip *"
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-linux64

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
  cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh generate.sh android
      cd ../s
      sh build.sh android
      cd deploy
      zip -rq ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-android-qt5


- job: android_qt6
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
  cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      sh environment.sh qt6
      sh generate.sh android
      cd ../s
      sh build.sh android
      cd deploy
      zip -rq ../libtorrent.zip *
  - publish: $(System.DefaultWorkingDirectory)/libtorrent.zip
    artifact: libtorrent-android-qt6
