#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win32
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: libtorrent-win32

- job: win64
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win64
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: libtorrent-win64

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS
  pool:
    vmImage: "macOS-latest"
  steps:
  - bash: |
      sh build.sh macOS
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: libtorrent-macOS
