#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh install.sh win32
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: libtorrent-win32

- job: win64
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh install.sh win64
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: libtorrent-win64
